#!/usr/bin/env bash
# Get the PID of the running "4-to_infinity_and_beyond" script
# Use "pgrep" to find the process with the exact name
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process was found
if [[ -z "$pid" ]]; then
	  echo "Process 4-to_infinity_and_beyond not found"
	    exit 1
fi

# Send SIGINT signal to the process with the found PID
kill -INT "$pid"
