#!/usr/bin/env bash
#disply a bash script
# Trap the SIGTERM signal (typically sent by Ctrl+C or kill)
trap 'echo "I am invincible!!!"' 15
while "true"
do
	echo "To infinity and beyond"
	sleep 2
done
